name: flutter_riverpod_todo_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.2.4+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2+1
  uuid: ^3.0.6
  shared_preferences: ^2.0.13
  backdrop: ^0.8.0
  url_launcher: ^6.0.20
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  share_plus: ^4.0.4
  file_picker: ^4.5.1
  carbon_icons: ^0.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300